/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.projectschedule.view;

import br.com.projectschedule.controll.Contact;
import br.com.projectschedule.controll.Phone;
import br.com.projectschedule.model.DAO;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author My&Lucas
 */
public class InsertContato extends javax.swing.JFrame {
    DAO cd = new DAO();
    Contact contact = new Contact();
    List<Phone> phones = new ArrayList<>();
    int number = 1;
    /**
     * Creates new form InsertContato
     */
    
    public InsertContato() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jAddNumber = new javax.swing.JButton();
        jName = new javax.swing.JTextField();
        jEmail = new javax.swing.JTextField();
        jTel01 = new javax.swing.JTextField();
        jDDD01 = new javax.swing.JTextField();
        jDDD02 = new javax.swing.JTextField();
        jDDD03 = new javax.swing.JTextField();
        jDDD04 = new javax.swing.JTextField();
        jDDD05 = new javax.swing.JTextField();
        jTel02 = new javax.swing.JTextField();
        jTel03 = new javax.swing.JTextField();
        jTel04 = new javax.swing.JTextField();
        jTel05 = new javax.swing.JTextField();
        jLDDD01 = new javax.swing.JLabel();
        jLDDD02 = new javax.swing.JLabel();
        jLDDD03 = new javax.swing.JLabel();
        jLDDD04 = new javax.swing.JLabel();
        jLDDD05 = new javax.swing.JLabel();
        jSubNumber = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Name: ");

        jLabel2.setText("E-mail");

        jLabel3.setText("Phone(s): ");

        jAddNumber.setText("+");
        jAddNumber.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jAddNumber.setBorderPainted(false);
        jAddNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddNumberActionPerformed(evt);
            }
        });

        jName.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jNamePropertyChange(evt);
            }
        });

        jDDD02.setEnabled(false);

        jDDD03.setEnabled(false);

        jDDD04.setEnabled(false);

        jDDD05.setEnabled(false);

        jTel02.setEnabled(false);

        jTel03.setEnabled(false);

        jTel04.setEnabled(false);

        jTel05.setEnabled(false);

        jLDDD01.setText("DDD");
        jLDDD01.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLDDD01PropertyChange(evt);
            }
        });

        jLDDD02.setText("DDD");
        jLDDD02.setEnabled(false);

        jLDDD03.setText("DDD");
        jLDDD03.setEnabled(false);

        jLDDD04.setText("DDD");
        jLDDD04.setEnabled(false);

        jLDDD05.setText("DDD");
        jLDDD05.setEnabled(false);

        jSubNumber.setText("-");
        jSubNumber.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSubNumber.setBorderPainted(false);
        jSubNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubNumberActionPerformed(evt);
            }
        });

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Confirmar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLDDD01)
                                .addComponent(jLDDD02))
                            .addComponent(jLDDD03)
                            .addComponent(jLDDD04)
                            .addComponent(jLDDD05, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDDD04, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                            .addComponent(jDDD05, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDDD01)
                            .addComponent(jDDD02)
                            .addComponent(jDDD03))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTel04, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTel03, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTel05, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTel02, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTel01, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(2, 2, 2)
                        .addComponent(jAddNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSubNumber))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jName))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jAddNumber)
                    .addComponent(jSubNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTel01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDDD01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLDDD01))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDDD02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTel02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLDDD02))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDDD03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTel03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLDDD03))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDDD04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTel04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLDDD04))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDDD05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTel05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLDDD05))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAddNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddNumberActionPerformed
       if(number < 5){
       number+=1;
       }
        SetEnable(number);
        System.out.println(number);
    }//GEN-LAST:event_jAddNumberActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        contact.setNome(jName.getText());
        contact.setEmail(jEmail.getText());
        System.out.println(contact);
        
        InsertListNumber(number);
        
        System.out.println(phones);
           
       cd.CreateContact(contact, phones, number);       
       
       Contacts ct = new Contacts();
       ct.setVisible(rootPaneCheckingEnabled);
       this.dispose(); 
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLDDD01PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLDDD01PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLDDD01PropertyChange

    private void jSubNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubNumberActionPerformed
         if(number > 1){
       number-=1;
       }
        SetDisable(number);
        System.out.println(number);
    }//GEN-LAST:event_jSubNumberActionPerformed

    private void jNamePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jNamePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jNamePropertyChange

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        cd.ReadContact();
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertContato().setVisible(true);
            }
        });
    }
    
    
    private void SetEnable(int num){
        switch(num){
            case 1:
                jLDDD01.setEnabled(rootPaneCheckingEnabled);
                jDDD01.setEnabled(rootPaneCheckingEnabled);
                jTel01.setEnabled(rootPaneCheckingEnabled);
                break;
            case 2:
                jLDDD02.setEnabled(rootPaneCheckingEnabled);
                jDDD02.setEnabled(rootPaneCheckingEnabled);
                jTel02.setEnabled(rootPaneCheckingEnabled);
                break;
            case 3:
                jLDDD03.setEnabled(rootPaneCheckingEnabled);
                jDDD03.setEnabled(rootPaneCheckingEnabled);
                jTel03.setEnabled(rootPaneCheckingEnabled);
                break;
            case 4:
                jLDDD04.setEnabled(rootPaneCheckingEnabled);
                jDDD04.setEnabled(rootPaneCheckingEnabled);
                jTel04.setEnabled(rootPaneCheckingEnabled);
                break;
            case 5:
                jLDDD05.setEnabled(rootPaneCheckingEnabled);
                jDDD05.setEnabled(rootPaneCheckingEnabled);
                jTel05.setEnabled(rootPaneCheckingEnabled);
                break;  
        }
        
        
    }
    private void SetDisable(int num){
        switch(num){
            case 4:
                jLDDD05.setEnabled(false);
                jDDD05.setEnabled(false);
                jTel05.setEnabled(false);
                break;
            case 3:
                jLDDD04.setEnabled(false);
                jDDD04.setEnabled(false);
                jTel04.setEnabled(false);
                break;
            case 2:
                jLDDD03.setEnabled(false);
                jDDD03.setEnabled(false);
                jTel03.setEnabled(false);
                break;
            case 1:
                jLDDD02.setEnabled(false);
                jDDD02.setEnabled(false);
                jTel02.setEnabled(false);
                break;
            case 0:
                jLDDD01.setEnabled(false);
                jDDD01.setEnabled(false);
                jTel01.setEnabled(false);
                break;
        }
    }
    
     void InsertListNumber(int num){
         phones.clear();
       switch(num){
            case 1:
                phones.add(new Phone(jDDD01.getText(),jTel01.getText()));
                break;
            case 2:
                phones.add(new Phone(jDDD01.getText(),jTel01.getText()));
                phones.add(new Phone(jDDD02.getText(),jTel02.getText()));
                break;
            case 3:
                phones.add(new Phone(jDDD01.getText(),jTel01.getText()));
                phones.add(new Phone(jDDD02.getText(),jTel02.getText()));
                phones.add(new Phone(jDDD03.getText(),jTel03.getText()));
                break;
            case 4:
                phones.add(new Phone(jDDD01.getText(),jTel01.getText()));
                phones.add(new Phone(jDDD02.getText(),jTel02.getText()));
                phones.add(new Phone(jDDD03.getText(),jTel03.getText()));
                phones.add(new Phone(jDDD04.getText(),jTel04.getText()));
                break;
            case 5:
                phones.add(new Phone(jDDD01.getText(),jTel01.getText()));
                phones.add(new Phone(jDDD02.getText(),jTel02.getText()));
                phones.add(new Phone(jDDD03.getText(),jTel03.getText()));
                phones.add(new Phone(jDDD04.getText(),jTel04.getText()));
                phones.add(new Phone(jDDD05.getText(),jTel05.getText()));
                break;    
       }
         
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddNumber;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JTextField jDDD01;
    private javax.swing.JTextField jDDD02;
    private javax.swing.JTextField jDDD03;
    private javax.swing.JTextField jDDD04;
    private javax.swing.JTextField jDDD05;
    private javax.swing.JTextField jEmail;
    private javax.swing.JLabel jLDDD01;
    private javax.swing.JLabel jLDDD02;
    private javax.swing.JLabel jLDDD03;
    private javax.swing.JLabel jLDDD04;
    private javax.swing.JLabel jLDDD05;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jSubNumber;
    private javax.swing.JTextField jTel01;
    private javax.swing.JTextField jTel02;
    private javax.swing.JTextField jTel03;
    private javax.swing.JTextField jTel04;
    private javax.swing.JTextField jTel05;
    // End of variables declaration//GEN-END:variables

}
